## Detector-level study with Pythia and Delphes

# Folder where to keep everything for MadMiner WH studies, on which we store Madgraph samples and all .h5 files (setup, analyzed events, ...)
main_dir: /lstore/titan/martafsilva/master_thesis/master_thesis_output/detector_level_pythia_and_delphes

# Folder where to keep all the plots 
plot_dir: /lstore/titan/martafsilva/master_thesis/master_thesis_output/detector_level_pythia_and_delphes/plots# Name of setup file (without the .h5)
# Name of setup file (without the .h5)

setup_file: setup 

#Name of the cards_folder
cards_folder_name: cards

# If running pythia, the path for the Pythia card
pythia_card: cards/pythia8_card.dat

# Path for MadGraph installation
mg_dir: /cvmfs/sw.el7/gcc63/madgraph/3.3.1/b01/

